config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do
    member do
      resources :messages
    end
  end
  get '/' => 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :message
end

app/models/message_group.rb
class MessageGroup < ApplicationRecord
  has_many :messages
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = MessageGroup.all.order(:updated_at)
  end

  def create
    @group = MessageGroup.new(params.require(:message_group).permit(:name))
    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def show
    @group = MessageGroup.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/groups/index.html.haml
.d-flex.flex-row-reverse
  %a.btn.btn-primary{href: new_group_path}新規作成
- if @groups.empty?
  まだグループがありません
- else
  - @groups.each do |group|
    %div
      =link_to(group.name, group_path(group))

app/views/groups/new.html.haml
= simple_form_for(@group || MessageGroup.new, url: groups_path, html: {class: 'form-group'}) do |f|
  .inpu
  = f.error_notification
  = f.input :name
  .d-flex.flex-row-reverse
    = f.submit '作成', class: 'btn btn-primary'

app/views/groups/show.html.haml
%h2=@group.name
%hr
#messages
  - @group.messages.each do |message|
    %div= message.name
    %div
      %p=message.message

= simple_form_for(@message || Message.new) do |f|
  = f.input :name
  %br
  = f.input :message
  = f.submit '投稿', class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>